[package]
name = "bevy-game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
bevy_common_assets = { version = "0.15.0", features = ["ron"] }
bevy_procedural_tilemaps = "0.2.0"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
